### ISSUE TITLE
Scan NYU IT Knowledge base and ensure proper linkage

### ISSUE THREAD

**Issue by andrewbattista** [andrewbattista/lgwg#42]
There are many cases where content in LibGuides refers to content in the NYUIT Knowledge base, and vice versa. We need someone to do a global site search and make sure that all references to the NYUIT knowledge base are accurate and reflect accurate information. Similarly, we could use someone who is familiar with the NYU IT knowledge base to make sure that information represented on that site is correct.

**Comment by coblezc** [comment]
_Process documentation_

For links to LibGuides in kbase articles:
- Contact IT Service Catalog team: request a report of all ServiceLink pages that contain links to pages on guides.nyu.edu
- Once report is received, review the kbase articles, manually test each LG link on each kbase page
- If links are broken or outdated, contact owner of page and ask them to update links. The report should contain info about page owner

For links to kbase articles in LibGuides pages:
- N.b. You will need admin permission for LG in order to run this query
- In the LG dashboard, go to Tools > Search & Replace
- Use the following search parameters:
	Search type: content item
	Check all 3 boxes
	Search for: enter the URL string here, e.g. nyu.service-now.com/servicelink/ & nyu.edu/servicelink
	Replace with: leave blank!
	Match type: contains
	Case type: insensitive
	Click Search button. n.b. don't click Search AND Replace!! 
- Go through each guide in the search results and check if the links to the kbase are working, pointing to up-to-date articles, and pointing to the correct article. If not, search for the appropriate kbase article or other resource and update the link in the guide
