### ISSUE TITLE
Enable the editorial workflow immediately to encourage a guide publication process

### ISSUE THREAD

**Issue by andrewbattista** [andrewbattista/lgwg#59]
We should prohibit the publication of new guides without the approval of the LibGuides Global Working Group. This will help us get a handle on our content as we do a cleanup and accessibility audit.

**Comment by gianaricci** [comment]
While I like this idea in theory, I think it may cause issues with the subject liaisons. I believe some liaisons work directly with professors to create guides for specific classes. To take away their ability to do so may affect their relationships with faculty. My suggestions would be to implement this more piecemeal by approaching guide creators individually and encouraging them not to produce additional guides until all their other guides are in check, rather than systematically implementing it as a hard rule.

**Comment by andrewbattista** [comment]
Understandable, @gianaricci  - we will definitely need to communicate this change, and the intention is to not rule out unmediated forever but just until we get the system in check. We can also communicate many of the viable options people will have (i.e., create course specific pages on existing guides, use another interface like Google Sites, Google docs, GitHub/Jekyll, etc.)

**Comment by Jem706** [comment]
@andrewbattista I think what @gianaricci is describing is one of the ways that guides have been used historically, but might fall outside of the way that lgwg is envisioning they be used in the future.

Perhaps the discussion should/could be moved to one about libguide best-practices or libguide use cases?
